-- MySQL Script generated by MySQL Workbench
-- 04/14/17 15:35:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`salads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`salads` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ingredients` (
  `id` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `caloricity` INT UNSIGNED NOT NULL,
  `weight` INT UNSIGNED NOT NULL,
  `salad_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `salad_id_idx` (`salad_id` ASC),
  CONSTRAINT `salad_id`
    FOREIGN KEY (`salad_id`)
    REFERENCES `mydb`.`salads` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`salads`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`salads` (`id`, `type`, `name`) VALUES (1, 'FruitSalad', 'Fruit salad');
INSERT INTO `mydb`.`salads` (`id`, `type`, `name`) VALUES (2, 'VegetableSalad', 'Vegetable salad');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`ingredients`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`ingredients` (`id`, `type`, `name`, `caloricity`, `weight`, `salad_id`) VALUES (1, 'Apple', 'Apple', 47, 200, 1);
INSERT INTO `mydb`.`ingredients` (`id`, `type`, `name`, `caloricity`, `weight`, `salad_id`) VALUES (2, 'Banana', 'Banana', 95, 100, 1);
INSERT INTO `mydb`.`ingredients` (`id`, `type`, `name`, `caloricity`, `weight`, `salad_id`) VALUES (3, 'Cucumber', 'Cucumber', 15, 200, 2);
INSERT INTO `mydb`.`ingredients` (`id`, `type`, `name`, `caloricity`, `weight`, `salad_id`) VALUES (4, 'Carrot', 'Carrot', 32, 100, 2);
INSERT INTO `mydb`.`ingredients` (`id`, `type`, `name`, `caloricity`, `weight`, `salad_id`) VALUES (5, 'Tomato', 'Tomato', 20, 100, 2);

COMMIT;

